"""add status and last_tested_at to connections

Revision ID: 9c2e5f45f8aa
Revises: a3612abd2e2c
Create Date: 2026-03-15 21:54:23.732118

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c2e5f45f8aa"
down_revision: str | Sequence[str] | None = "a3612abd2e2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connections",
        sa.Column("status", sa.String(length=20), server_default="disconnected", nullable=False),
    )
    op.add_column(
        "connections", sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "connections",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connections", "updated_at")
    op.drop_column("connections", "last_tested_at")
    op.drop_column("connections", "status")
    # ### end Alembic commands ###
