"""make bookmark message_id nullable

Revision ID: a3612abd2e2c
Revises: ba968e5cdfbf
Create Date: 2026-03-15 21:22:33.422274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3612abd2e2c"
down_revision: Union[str, Sequence[str], None] = "ba968e5cdfbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookmarks", "message_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("bookmarks_message_id_fkey"), "bookmarks", type_="foreignkey")
    op.create_foreign_key(
        None, "bookmarks", "messages", ["message_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bookmarks", type_="foreignkey")
    op.create_foreign_key(
        op.f("bookmarks_message_id_fkey"),
        "bookmarks",
        "messages",
        ["message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("bookmarks", "message_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
