import { useMemo, useCallback, useState, useRef } from "react";
import { AlertCircle, TrendingUp, Image, FileCode } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Data, Layout, Config } from "plotly.js";
import Plot from "react-plotly.js";
import { exportChart, exportKpiCard } from "./chart-export";

/** Plotly chart config as generated by the AI agent. */
export interface ChartConfig {
  type: "line" | "bar" | "pie" | "scatter" | "kpi";
  data?: Data[];
  layout?: Partial<Layout>;
  config?: Partial<Config>;
  /** KPI-specific fields (when type === "kpi") */
  kpiValue?: string | number;
  kpiLabel?: string;
  kpiDelta?: number | null;
  kpiPrefix?: string;
  kpiSuffix?: string;
}

interface ChartRendererProps {
  chartConfig: ChartConfig;
  /** Theme for adapting colors */
  resolvedTheme?: "light" | "dark";
  className?: string;
}

/** Default Plotly config with interactive features enabled. */
const DEFAULT_PLOTLY_CONFIG: Partial<Config> = {
  responsive: true,
  displayModeBar: true,
  displaylogo: false,
  modeBarButtonsToRemove: ["lasso2d", "autoScale2d"],
  scrollZoom: true,
};

function getThemeLayout(resolvedTheme: "light" | "dark"): Partial<Layout> {
  const isDark = resolvedTheme === "dark";
  return {
    paper_bgcolor: "transparent",
    plot_bgcolor: isDark ? "rgba(30, 30, 40, 0.5)" : "rgba(250, 250, 252, 0.5)",
    font: {
      color: isDark ? "#e2e8f0" : "#1e293b",
      family: "Inter, system-ui, sans-serif",
    },
    xaxis: {
      gridcolor: isDark ? "rgba(148, 163, 184, 0.15)" : "rgba(148, 163, 184, 0.25)",
      zerolinecolor: isDark ? "rgba(148, 163, 184, 0.3)" : "rgba(148, 163, 184, 0.4)",
    },
    yaxis: {
      gridcolor: isDark ? "rgba(148, 163, 184, 0.15)" : "rgba(148, 163, 184, 0.25)",
      zerolinecolor: isDark ? "rgba(148, 163, 184, 0.3)" : "rgba(148, 163, 184, 0.4)",
    },
    margin: { t: 40, r: 20, b: 40, l: 50 },
  };
}

function isValidChartConfig(config: unknown): config is ChartConfig {
  if (!config || typeof config !== "object") return false;
  const c = config as Record<string, unknown>;
  if (typeof c.type !== "string") return false;
  const validTypes = ["line", "bar", "pie", "scatter", "kpi"];
  if (!validTypes.includes(c.type)) return false;

  if (c.type === "kpi") {
    return c.kpiValue !== undefined && c.kpiValue !== null;
  }

  if (!Array.isArray(c.data)) return false;
  return true;
}

function hasChartData(config: ChartConfig): boolean {
  if (config.type === "kpi") {
    return config.kpiValue !== undefined && config.kpiValue !== null;
  }
  if (!config.data || config.data.length === 0) return false;

  return config.data.some((trace) => {
    const t = trace as Record<string, unknown>;
    const x = t.x as unknown[] | undefined;
    const y = t.y as unknown[] | undefined;
    const values = t.values as unknown[] | undefined;
    const labels = t.labels as unknown[] | undefined;

    if (Array.isArray(x) && x.length > 0) return true;
    if (Array.isArray(y) && y.length > 0) return true;
    if (Array.isArray(values) && values.length > 0) return true;
    if (Array.isArray(labels) && labels.length > 0) return true;
    return false;
  });
}

/** Floating toast for export errors. */
function ExportErrorToast({
  message,
  onDismiss,
}: {
  message: string;
  onDismiss: () => void;
}) {
  return (
    <div
      data-testid="export-error-toast"
      className="absolute bottom-2 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 rounded-md border border-destructive/50 bg-destructive/10 px-3 py-2 text-xs text-destructive shadow-sm"
    >
      <AlertCircle className="size-3.5 shrink-0" />
      <span>{message}</span>
      <button
        onClick={onDismiss}
        className="ml-1 text-destructive hover:text-destructive/80"
        aria-label="Dismiss error"
      >
        &times;
      </button>
    </div>
  );
}

/** Export toolbar shown on hover over chart containers. */
function ExportToolbar({
  onExportPng,
  onExportSvg,
  isExporting,
}: {
  onExportPng: () => void;
  onExportSvg?: () => void;
  isExporting: boolean;
}) {
  return (
    <div
      data-testid="chart-export-toolbar"
      className="absolute right-2 top-2 z-10 flex items-center gap-1 rounded-md border border-border bg-background/90 p-1 shadow-sm opacity-0 transition-opacity group-hover:opacity-100"
    >
      <button
        data-testid="export-png-btn"
        className="inline-flex items-center gap-1 rounded px-2 py-1 text-xs text-muted-foreground hover:bg-accent hover:text-foreground disabled:opacity-50"
        onClick={onExportPng}
        disabled={isExporting}
        aria-label="Export as PNG"
        title="Export as PNG"
      >
        <Image className="size-3" />
        PNG
      </button>
      {onExportSvg && (
        <button
          data-testid="export-svg-btn"
          className="inline-flex items-center gap-1 rounded px-2 py-1 text-xs text-muted-foreground hover:bg-accent hover:text-foreground disabled:opacity-50"
          onClick={onExportSvg}
          disabled={isExporting}
          aria-label="Export as SVG"
          title="Export as SVG"
        >
          <FileCode className="size-3" />
          SVG
        </button>
      )}
    </div>
  );
}

/** KPI card for single scalar values. */
function KpiCard({
  config,
  className,
}: {
  config: ChartConfig;
  className?: string;
}) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);

  const handleExportPng = useCallback(async () => {
    if (!cardRef.current) return;
    setIsExporting(true);
    setExportError(null);
    try {
      await exportKpiCard(
        cardRef.current,
        (config.kpiLabel ?? "kpi").replace(/[^a-zA-Z0-9]/g, "_"),
      );
    } catch {
      setExportError("Failed to export KPI card");
    } finally {
      setIsExporting(false);
    }
  }, [config.kpiLabel]);

  const deltaColor =
    config.kpiDelta != null
      ? config.kpiDelta > 0
        ? "text-emerald-500"
        : config.kpiDelta < 0
          ? "text-red-500"
          : "text-muted-foreground"
      : null;

  const deltaSign = config.kpiDelta != null && config.kpiDelta > 0 ? "+" : "";

  return (
    <div className="group relative">
      <ExportToolbar
        onExportPng={handleExportPng}
        isExporting={isExporting}
      />
      <div
        ref={cardRef}
        data-testid="kpi-card"
        className={cn(
          "flex flex-col items-center justify-center gap-2 rounded-md border border-border bg-card p-6",
          className,
        )}
      >
        <span className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
          {config.kpiLabel ?? "Value"}
        </span>
        <span className="text-3xl font-bold text-foreground" data-testid="kpi-value">
          {config.kpiPrefix ?? ""}
          {typeof config.kpiValue === "number"
            ? config.kpiValue.toLocaleString()
            : config.kpiValue}
          {config.kpiSuffix ?? ""}
        </span>
        {config.kpiDelta != null && (
          <span
            className={cn("flex items-center gap-1 text-sm font-medium", deltaColor)}
            data-testid="kpi-delta"
          >
            <TrendingUp className="size-3.5" />
            {deltaSign}
            {config.kpiDelta}%
          </span>
        )}
      </div>
      {exportError && (
        <ExportErrorToast
          message={exportError}
          onDismiss={() => setExportError(null)}
        />
      )}
    </div>
  );
}

/** Renders a Plotly chart or KPI card from an AI-generated config. */
export function ChartRenderer({
  chartConfig,
  resolvedTheme = "light",
  className,
}: ChartRendererProps) {
  const [hasError, setHasError] = useState(false);

  const handleError = useCallback(() => {
    setHasError(true);
  }, []);

  // Validate config
  if (!isValidChartConfig(chartConfig)) {
    return (
      <div
        data-testid="chart-error"
        className={cn(
          "flex items-center justify-center gap-2 rounded-md border border-destructive/30 bg-destructive/5 p-6 text-sm text-destructive",
          className,
        )}
      >
        <AlertCircle className="size-4" />
        <span>Cannot render chart</span>
      </div>
    );
  }

  // Check for empty data
  if (!hasChartData(chartConfig)) {
    return (
      <div
        data-testid="chart-no-data"
        className={cn(
          "flex items-center justify-center gap-2 rounded-md border border-border bg-muted/30 p-6 text-sm text-muted-foreground",
          className,
        )}
      >
        <AlertCircle className="size-4" />
        <span>No data</span>
      </div>
    );
  }

  // KPI card
  if (chartConfig.type === "kpi") {
    return <KpiCard config={chartConfig} className={className} />;
  }

  // Plotly chart rendering
  return (
    <PlotlyChart
      chartConfig={chartConfig}
      resolvedTheme={resolvedTheme}
      className={className}
      hasError={hasError}
      onError={handleError}
    />
  );
}

function PlotlyChart({
  chartConfig,
  resolvedTheme,
  className,
  hasError,
  onError,
}: {
  chartConfig: ChartConfig;
  resolvedTheme: "light" | "dark";
  className?: string;
  hasError: boolean;
  onError: () => void;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);

  const themeLayout = useMemo(() => getThemeLayout(resolvedTheme), [resolvedTheme]);

  const mergedLayout = useMemo((): Partial<Layout> => {
    return {
      ...themeLayout,
      ...(chartConfig.layout ?? {}),
      xaxis: { ...themeLayout.xaxis, ...(chartConfig.layout?.xaxis ?? {}) },
      yaxis: { ...themeLayout.yaxis, ...(chartConfig.layout?.yaxis ?? {}) },
      font: { ...themeLayout.font, ...(chartConfig.layout?.font ?? {}) },
      autosize: true,
      transition: {
        duration: 300,
        easing: "cubic-in-out",
      },
    };
  }, [chartConfig.layout, themeLayout]);

  const mergedConfig = useMemo((): Partial<Config> => {
    return {
      ...DEFAULT_PLOTLY_CONFIG,
      ...(chartConfig.config ?? {}),
    };
  }, [chartConfig.config]);

  const getPlotlyDiv = useCallback((): HTMLElement | null => {
    if (!containerRef.current) return null;
    const plotDiv = containerRef.current.querySelector(".js-plotly-plot");
    return plotDiv as HTMLElement | null;
  }, []);

  const chartTitle = (chartConfig.layout?.title as string) ?? "chart";
  const sanitizedTitle = chartTitle.replace(/[^a-zA-Z0-9]/g, "_");

  const handleExportPng = useCallback(async () => {
    const plotDiv = getPlotlyDiv();
    if (!plotDiv) return;
    setIsExporting(true);
    setExportError(null);
    try {
      await exportChart(plotDiv, {
        format: "png",
        filename: sanitizedTitle,
        scale: 2,
      });
    } catch {
      setExportError("Failed to export chart as PNG");
    } finally {
      setIsExporting(false);
    }
  }, [getPlotlyDiv, sanitizedTitle]);

  const handleExportSvg = useCallback(async () => {
    const plotDiv = getPlotlyDiv();
    if (!plotDiv) return;
    setIsExporting(true);
    setExportError(null);
    try {
      await exportChart(plotDiv, {
        format: "svg",
        filename: sanitizedTitle,
      });
    } catch {
      setExportError("Failed to export chart as SVG");
    } finally {
      setIsExporting(false);
    }
  }, [getPlotlyDiv, sanitizedTitle]);

  if (hasError) {
    return (
      <div
        data-testid="chart-error"
        className={cn(
          "flex items-center justify-center gap-2 rounded-md border border-destructive/30 bg-destructive/5 p-6 text-sm text-destructive",
          className,
        )}
      >
        <AlertCircle className="size-4" />
        <span>Cannot render chart</span>
      </div>
    );
  }

  return (
    <div className="group relative">
      <ExportToolbar
        onExportPng={handleExportPng}
        onExportSvg={handleExportSvg}
        isExporting={isExporting}
      />
      <div
        ref={containerRef}
        data-testid="chart-container"
        className={cn("w-full overflow-hidden rounded-md border border-border", className)}
      >
        <Plot
          data={chartConfig.data!}
          layout={mergedLayout}
          config={mergedConfig}
          useResizeHandler
          className="h-[300px] w-full"
          style={{ width: "100%", height: "300px" }}
          onError={onError}
        />
      </div>
      {exportError && (
        <ExportErrorToast
          message={exportError}
          onDismiss={() => setExportError(null)}
        />
      )}
    </div>
  );
}
